(() => {
  'use strict';
  const SESSION_KEY='general-sales-admin-v7-local';
  let token=localStorage.getItem(SESSION_KEY)||'',companies=[];
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmtDate=ts=>ts?new Date(Number(ts)).toLocaleDateString('ar-EG',{year:'numeric',month:'2-digit',day:'2-digit'}):'—';
  async function api(path,options={}){if(!window.CashTopCloud?.request)throw new Error('ملف الربط المباشر مع Turso غير محمل.');try{return await window.CashTopCloud.request(path,options,token||'');}catch(e){e.code=e.code||'';if(['SESSION_REQUIRED','SESSION_EXPIRED'].includes(e.code))logoutLocal();throw e;}}
  function toast(msg,error=false){const t=$('adminToast');t.textContent=msg;t.style.background=error?'#991b1b':'#0f172a';t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,2800);}
  function logoutLocal(){token='';localStorage.removeItem(SESSION_KEY);$('adminShell').hidden=true;$('adminLogin').hidden=false;}
  function showShell(){$('adminLogin').hidden=true;$('adminShell').hidden=false;}
  async function login(password){const d=await api('/admin/login',{method:'POST',body:JSON.stringify({password})});token=d.token;localStorage.setItem(SESSION_KEY,token);showShell();loadCompanies().catch(e=>{toast(e.message||'تعذر تحميل الشركات. اضغط تحديث للمحاولة مرة أخرى.',true);});return true;}
  async function validate(){if(!token)return false;try{await api('/admin/validate',{method:'POST'});return true;}catch{return false;}}
  function companyState(c){if(c.deleted)return['محذوفة','deleted'];if(c.status!=='active')return['موقوفة','stopped'];if(Number(c.expiresAt)<=Date.now())return['منتهية','expired'];return['فعالة','active'];}
  function renderCompanies(){const q=$('companySearch').value.trim().toLowerCase(),rows=companies.filter(c=>!q||String(c.name).toLowerCase().includes(q));$('companiesCount').textContent=companies.filter(c=>!c.deleted).length;$('activeCount').textContent=companies.filter(c=>companyState(c)[1]==='active').length;$('inactiveCount').textContent=companies.filter(c=>['stopped','expired'].includes(companyState(c)[1])).length;$('companiesGrid').innerHTML=rows.length?rows.map(c=>{const [label,cls]=companyState(c),days=Math.ceil((Number(c.expiresAt)-Date.now())/86400000);return `<article class="company-card ${cls}"><div class="company-top"><div><h4>${esc(c.settings?.companyName||c.name)}</h4><small>ID: ${esc(c.id)}</small></div><span class="status ${cls}">${label}</span></div><div class="company-meta"><div><span>ينتهي</span><strong>${fmtDate(c.expiresAt)}</strong></div><div><span>المدة المتبقية</span><strong>${days>0?days+' يوم':'منتهي'}</strong></div><div><span>المستخدمون النشطون</span><strong>${Number(c.activeUsers||0)}</strong></div><div><span>المفتاح</span><strong>•••• ${esc(c.keyHint||'')}</strong></div></div>${c.deleted?'':`<div class="company-actions"><button class="blue" data-edit="${esc(c.id)}">تعديل</button><button class="${c.status==='active'?'amber':'green'}" data-status="${esc(c.id)}" data-next="${c.status==='active'?'stopped':'active'}">${c.status==='active'?'إيقاف':'تشغيل'}</button><button class="green" data-extend="${esc(c.id)}">تمديد</button><button class="blue" data-rotate="${esc(c.id)}">مفتاح جديد</button><button class="red" data-delete="${esc(c.id)}">حذف</button></div>`}</article>`}).join(''):'<div style="padding:30px;text-align:center;color:#64748b">لا توجد شركات.</div>';bindCompanyActions();}
  async function loadCompanies(){const d=await api('/admin/companies');companies=d.rows||[];renderCompanies();}
  function showKey(key,name='مفتاح الشركة'){$('generatedKey').textContent=key;$('keyCompanyName').textContent=name;$('keyModal').hidden=false;}
  function bindCompanyActions(){document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{try{await api('/admin/companies/update',{method:'POST',body:JSON.stringify({id:b.dataset.status,status:b.dataset.next})});toast('تم تحديث حالة الشركة.');await loadCompanies();}catch(e){toast(e.message,true);}});document.querySelectorAll('[data-extend]').forEach(b=>b.onclick=async()=>{const days=Number(prompt('عدد أيام التمديد:',30));if(!days||days<1)return;try{await api('/admin/companies/update',{method:'POST',body:JSON.stringify({id:b.dataset.extend,extendDays:days})});toast('تم تمديد المفتاح.');await loadCompanies();}catch(e){toast(e.message,true);}});document.querySelectorAll('[data-rotate]').forEach(b=>b.onclick=async()=>{if(!confirm('إنشاء مفتاح جديد؟ سيتم إنهاء جلسات الشركة الحالية.'))return;try{const c=companies.find(x=>x.id===b.dataset.rotate),d=await api('/admin/companies/rotate-key',{method:'POST',body:JSON.stringify({id:b.dataset.rotate})});showKey(d.licenseKey,c?.name||'مفتاح جديد');await loadCompanies();}catch(e){toast(e.message,true);}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف الشركة سيوقف الدخول فورًا. متابعة؟'))return;try{await api('/admin/companies/delete',{method:'POST',body:JSON.stringify({id:b.dataset.delete})});toast('تم حذف الشركة وإبطال جلساتها.');await loadCompanies();}catch(e){toast(e.message,true);}});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const c=companies.find(x=>x.id===b.dataset.edit);if(!c)return;const name=prompt('اسم الشركة:',c.settings?.companyName||c.name);if(name===null)return;const date=prompt('تاريخ الانتهاء YYYY-MM-DD:',new Date(Number(c.expiresAt)).toISOString().slice(0,10));if(date===null)return;const ts=Date.parse(date+'T23:59:59');if(!Number.isFinite(ts)){toast('تاريخ غير صالح.',true);return;}try{await api('/admin/companies/update',{method:'POST',body:JSON.stringify({id:c.id,name,expiresAt:ts,settings:{...c.settings,companyName:name}})});toast('تم تعديل الشركة.');await loadCompanies();}catch(e){toast(e.message,true);}});}
  $('adminLoginForm').onsubmit=async e=>{e.preventDefault();const btn=$('adminLoginBtn'),msg=$('adminLoginMsg');msg.hidden=true;btn.disabled=true;btn.textContent='جاري الدخول...';try{await login($('adminPassword').value);}catch(err){msg.textContent=err.message;msg.hidden=false;}finally{btn.disabled=false;btn.textContent='دخول لوحة الأدمن';}};
  $('newCompanyBtn').onclick=()=>{$('companyForm').reset();$('companyForm').days.value=30;$('companyForm').ownerName.value='مدير الشركة';$('companyForm').ownerUsername.value='admin';$('companyModal').hidden=false;};
  $('closeCompanyModal').onclick=$('cancelCompanyBtn').onclick=()=>{$('companyModal').hidden=true;};
  $('companyForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={name:f.get('name'),days:Number(f.get('days')),ownerName:f.get('ownerName'),ownerUsername:f.get('ownerUsername'),ownerPassword:f.get('ownerPassword'),settings:{companyName:f.get('name'),phone:f.get('phone'),whatsapp:f.get('whatsapp'),email:f.get('email'),taxNumber:f.get('taxNumber'),commercialRegistration:f.get('commercialRegistration'),website:f.get('website'),address:f.get('address'),logoUrl:f.get('logoUrl')}};try{const d=await api('/admin/companies/create',{method:'POST',body:JSON.stringify(payload)});$('companyModal').hidden=true;showKey(d.licenseKey,payload.name);toast('تم إنشاء الشركة.');await loadCompanies();}catch(err){toast(err.message,true);}};
  $('copyKeyBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('generatedKey').textContent);toast('تم نسخ المفتاح.');}catch{toast('انسخ المفتاح يدويًا.',true);}};$('closeKeyModal').onclick=()=>{$('keyModal').hidden=true;};
  $('adminLogoutBtn').onclick=async()=>{try{await api('/admin/logout',{method:'POST'});}catch{}logoutLocal();};$('refreshBtn').onclick=()=>loadCompanies().catch(e=>toast(e.message,true));$('companySearch').oninput=renderCompanies;
  $('adminPasswordForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/admin/password',{method:'POST',body:JSON.stringify({currentPassword:f.get('currentPassword'),newPassword:f.get('newPassword')})});e.currentTarget.reset();toast('تم تغيير كلمة مرور الأدمن.');}catch(err){toast(err.message,true);}};
  if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
  (async()=>{if(await validate()){showShell();loadCompanies().catch(e=>toast(e.message||'تعذر تحميل الشركات. اضغط تحديث للمحاولة مرة أخرى.',true));}else logoutLocal();})().catch(()=>logoutLocal());
})();
